INSERT INTO JAVARUSHCRUD.TEST (NAME, AGE, IS_ADMIN) VALUES ('Dude', '18', '0');
INSERT INTO JAVARUSHCRUD.TEST (NAME, AGE, IS_ADMIN) VALUES ('Fella', '28', '0');
INSERT INTO JAVARUSHCRUD.TEST (NAME, AGE, IS_ADMIN) VALUES ('Comrade', '40', '1');
INSERT INTO JAVARUSHCRUD.TEST (NAME, AGE, IS_ADMIN) VALUES ('Comandante', '68', '1');
INSERT INTO JAVARUSHCRUD.TEST (NAME, AGE, IS_ADMIN) VALUES ('Princess', '18', '0');
INSERT INTO JAVARUSHCRUD.TEST (NAME, AGE, IS_ADMIN) VALUES ('Drake', '29', '0');